# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 975de7f7372befddd7650f88f307bcc2b9175c3af5e30b60fa94ad62df7f4ccb3b9d99ffc8ef06c70a43ebd3898863707a4ca75671c7b9b431d73d622b806b56

test:
  secret_key_base: 3600f7f7b3b6247e1c632cef04eaff8894cb4b9d834b58deefacb6808c152b90503ff8ccf9796c380786d6681230a4e0408914339e375e97afed17d20a227505

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
